### ISSUE TITLE
How to spawn 'autopilot NPC vehicle'

### ISSUE THREAD

**Issue by Kim-mins** [evshary/autoware_carla_launch#8] opened 2023-06-16 08:55 UTC
Hi @evshary
I have one more question about running Autoware on Carla with **autopilot NPC Vehicle**.
I'm currently running bridge and autoware on docker container (one container for each), and I'm working on **host PC** to spawn NPC vehicle.
However, when I spawn NPC vehicles, they do not move(actually moving with the speed about 0.1km/h) but Autoware works well.
And after about 150 seconds(2:30 minutes, on pygame UI), I could see the vehicles start to move, but Autoware and RViz stop(literally they do not make any response.. no updates are made).

It can be the issue from me because I create another carla client on host PC, but I cannot know..
Could you please tell me the way to generate NPC vehicle properly?

**Comment by Kim-mins** [comment] 2023-06-18 09:15
I just found that the bridge terminates after about 150 seconds with the log below:
```bash
 INFO  zenoh_carla_bridge::bridge::vehicle_bridge > Detect a vehicle autopilot
 INFO  zenoh_carla_bridge                         > Actor 1606 created
terminate called after throwing an instance of 'std::runtime_error'
  what():  Responding error from function get_wheel_steer_angle: Actor could not be found in the registry.  Actor Id: 1552
Aborted
```
To my knowledge, this error occurs when the actor(the actor with the id 1552, in this case.) is destroyed from carla simulator.
I've observed that **Carla automatically removes the vehicle itself** if it stops too long, and so I guess the reason of the termination of the bridge is that 1) vehicle stops too long, 2) the vehicle is destroyed by Carla after about 150 seconds and 3) the bridge eventually terminates (due to the destroyed vehicles).

But the other NPC vehicles moves after the termination of the bridge, so it seems like **the bridge is not compatible with autopilot NPC Vehicles**.
This can be the problem of my side, but maybe you can give me some hints for the conclusion.. Thank you in advance!

**Comment by evshary** [comment] 2023-06-19 02:09
Does the issue only happen while adding NPC vehicles?
Maybe you can provide me with a way how to reproduce it. I guess there is something wrong with the bridge.
I'll try to find some time to fix it.

**Comment by evshary** [comment] 2023-06-20 01:34
Thanks for your steps to reproduce the bugs. I'll try it on my side.

**Comment by evshary** [comment] 2023-06-21 06:41
@Kim-mins I think the issue is fixed by #10 . Maybe you can try and give me some feedback.

**Comment by Kim-mins** [comment] 2023-06-21 06:55
Thank you so much @evshary!! I always appreciate to your hard work!
I have little time to check it now, so I think I can run the code a bit later.
I'll mention you after the check! Thank you!

**Comment by Kim-mins** [comment] 2023-06-23 05:00
Thank you @evshary! I just tested the driving with NPC vehicle, and everything works fine.
I really appreciate to your help!!! Thank you!

**Closed** 2023-06-23 05:00 UTC
